---
version: "3.8"

volumes:
  "tomcat_logs":
  "tomcat_work":
  "tomcat_temp":

services:

  "nginx":
    image: "nginx"
    volumes:
      - type: "bind"
        source: "./src/main/nginx/nginx.conf"
        target: "/etc/nginx/nginx.conf"
        read_only: true
    ports:
      - published: 60080
        target: 80
    links:
      - "tomcat"
    depends_on:
      "tomcat":
        condition: "service_healthy"
    healthcheck:
      test: "curl -f http://localhost/"
      interval: "9s"
      timeout: "2s"
      retries: 1
      start_period: "1s"

  "tomcat":
    build: "./"
    volumes:
      - type: "bind"
        source: "./src/test"
        target: "/srv"
        read_only: true
      - type: "bind"
        source: "./src/main/tomcat/conf"
        target: "/usr/local/tomcat/conf"
        read_only: true
      - type: "volume"
        source: "tomcat_logs"
        target: "/usr/local/tomcat/logs"
      - type: "volume"
        source: "tomcat_work"
        target: "/usr/local/tomcat/work"
      - type: "volume"
        source: "tomcat_temp"
        target: "/usr/local/tomcat/temp"
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: "10s"
      timeout: "2s"
      retries: 1
      start_period: "3s"
